# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [ ]:
import numpy as np
arr1=np.arange(12)
arr1=arr1.reshape(3,4)
print('\n\n',arr1)
arr2=np.array([[9,8,7,6],
               [3,4,5,6],
               [1,3,2,9]])
conc_h=np.concatenate((arr1,arr2),axis=1)
print('\n\n',conc_h)

conc_v=np.concatenate((arr1,arr2),axis=0)
print('\n\n',conc_v)



 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


 [[ 0  1  2  3  9  8  7  6]
 [ 4  5  6  7  3  4  5  6]
 [ 8  9 10 11  1  3  2  9]]


 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 9  8  7  6]
 [ 3  4  5  6]
 [ 1  3  2  9]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [4]:
#code here
def classify_emails(lists_email):
  important=[]
  promotions=[]
  spam=[]
  for email in lists_email:
    if 'important' in email:
      important.append(email)
    if 'promotion' in email or 'deal' in email:
      promotions.append(email)
    if 'spam' in email or 'fake' in  email:
      spam.append(email)
  print('Important Emails', important)
  print('Promotions Emails', promotions)
  print('Spam Emails', spam)
list_emails=[]
print("Enter q to quit")
data=input('\nEnter your email: ')
while data != 'q':
  list_emails.append(data)
  data=input('Enter your email: ')
print('\n')
classify_emails(list_emails)


Enter q to quit

Enter your email: This is an important email
Enter your email: this is promotion 
Enter your email: spam is what this email looks like 
Enter your email: sale and marketing are mostly done through promotion
Enter your email: q


Important Emails ['This is an important email']
Promotions Emails ['this is promotion ', 'sale and marketing are mostly done through promotion']
Spam Emails ['spam is what this email looks like ']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [2]:
#code here
spanish_dict = {
    "elections": "elecciones",
    "party": "fiesta",
    "holidays": "vacaciones",
    "hello": "hola",
    "enjoying": "disfrutando",
    "traveling": "viajando",
}

def translate_word(word):
    if word in spanish_dict:
        return spanish_dict[word]
    else:
        return "Translation not available"

while True:
    word = input("Enter an English word (or 'q' to quit): ").lower()

    if word == 'q':
        print("Goodbye!")
        break

    translation = translate_word(word)
    print("Translation: ", translation)


Enter an English word (or 'q' to quit): hello
Translation:  hola
Enter an English word (or 'q' to quit): party
Translation:  fiesta
Enter an English word (or 'q' to quit): traveling
Translation:  viajando
Enter an English word (or 'q' to quit): q
Goodbye!


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [1]:
import pandas as pd
data=pd.read_csv('https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv')
data

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [3]:
total_global_sales = data['Global_Sales'].sum()
total_global_sales

8920.44

In [9]:
max_index=data['Global_Sales'].idxmax()
data['Name'][max_index]

'Wii Sports'

In [12]:
NA_avg=data['NA_Sales'].mean()
EU_Sales_avg=data['EU_Sales'].mean()
JP_Sales_avg=data['JP_Sales'].mean()
Other_Sales_avg=data['Other_Sales'].mean()
print("Average sales are ")
print("NA sales average: ",NA_avg)
print("EU sales average: ",EU_Sales_avg)
print("JP sales average: ",JP_Sales_avg)
print("Other sales average: ",Other_Sales_avg)

Average sales are 
NA sales average:  0.26466742981082064
EU sales average:  0.14665200626581515
JP sales average:  0.077781660441017
Other sales average:  0.0480630196409206


In [17]:
genre_sales = data.groupby('Genre')['Global_Sales'].sum()
sorted_genre_sales = genre_sales.sort_values(ascending=False)
top_5_genres = sorted_genre_sales.head(5)
print("Top 5 most popular game genres based on global sales:")
print(top_5_genres)

Top 5 most popular game genres based on global sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [22]:
genre_sales_na = data.groupby('Genre')['NA_Sales'].sum()
genre_sales_eu = data.groupby('Genre')['EU_Sales'].sum()
genre_sales_jp = data.groupby('Genre')['JP_Sales'].sum()
genre_sales_other = data.groupby('Genre')['Other_Sales'].sum()

genre_region_sales = pd.DataFrame({
    'NA_Sales': genre_sales_na,
    'EU_Sales': genre_sales_eu,
    'JP_Sales': genre_sales_jp,
    'Other_Sales': genre_sales_other
})

print("Total sales for each genre in each region:")
print(genre_region_sales)
most_popular_genre_na = genre_region_sales['NA_Sales'].idxmax()

print("\nMost popular genre in North America:", most_popular_genre_na)

Total sales for each genre in each region:
              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36

Most popular genre in North America: Action


In [23]:
data[len(data)-10:]

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [24]:
genre_sales = data.groupby('Platform')['Global_Sales'].sum()
sorted_genre_sales = genre_sales.sort_values(ascending=False)
top_platforms = sorted_genre_sales.head(3)
print("Top 3 most popular platform based on global sales:")
print(top_platforms)

Top 3 most popular platform based on global sales:
Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [26]:
genre_global_sales = data.groupby('Genre')['Global_Sales'].sum()
total_global_sales = data['Global_Sales'].sum()
market_share = (genre_global_sales / total_global_sales) * 100
print("Market share :")
print(market_share)

Market share :
Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [28]:
corr_coeff = data['NA_Sales'].corr(data['EU_Sales'])
corr_coeff

0.7677267483702631

In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
